In [13]:
library(sf)
library(dplyr)
library(foreign)

In [21]:
Crailshppath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdC.shp"
Craildbfpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdC.dbf"
Crailprjpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdC.prj"
Crailshxpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdC.shx"

Lrailshppath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdL.shp"
Lraildbfpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdL.dbf"
Lrailprjpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdL.prj"
Lrailshxpath<-"Dati_progetto1\\DATA\\Countries\\FR\\RailrdL.shx"

In [22]:
railCshp<- data.frame(st_read(Crailshppath))
railCdbf<- data.frame(read.dbf(Craildbfpath))
railCshx<- data.frame(st_read(Crailshxpath))

railLshp<- data.frame(st_read(Lrailshppath))
railLdbf<- data.frame(read.dbf(Lraildbfpath))
railLshx<- data.frame(st_read(Lrailshxpath))

Reading layer `RailrdC' from data source
  `C:\R_notebooks_ComplexNets\progettodata\Dati_progetto1\DATA\Countries\FR\RailrdC.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 620 features and 14 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -4.479926 ymin: 42.69609 xmax: 7.850915 ymax: 51.03022
Geodetic CRS:  ETRS89
Reading layer `RailrdC' from data source
  `C:\R_notebooks_ComplexNets\progettodata\Dati_progetto1\DATA\Countries\FR\RailrdC.shx'
  using driver `ESRI Shapefile'
Simple feature collection with 620 features and 14 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -4.479926 ymin: 42.69609 xmax: 7.850915 ymax: 51.03022
Geodetic CRS:  ETRS89
Reading layer `RailrdL' from data source
  `C:\R_notebooks_ComplexNets\progettodata\Dati_progetto1\DATA\Countries\FR\RailrdL.shp'
  using driver `ESRI Shapefile'
Simple feature collection with 4606 features and 24 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: -4.479926 ymin: 42.41993 xmax: 8.196119 ymax: 51.04109
Geodetic CRS:  ETRS89
Reading layer `RailrdL' from data source
  `C:\R_notebooks_ComplexNets\progettodata\Dati_progetto1\DATA\Countries\FR\RailrdL.shx'
  using driver `ESRI Shapefile'
Simple feature collection with 4606 features and 24 fields
Geometry type: LINESTRING
Dimension:     XY
Bounding box:  xmin: -4.479926 ymin: 42.41993 xmax: 8.196119 ymax: 51.04109
Geodetic CRS:  ETRS89

In [27]:
head(railLshp)

  FCsubtype inspireId                                          beginLifes
1 1         _EG.EGM.RailrdL:fa0109ed-8174-494a-be41-a9f2e82d05 2018-08-02
2 1         _EG.EGM.RailrdL:2d025ab6-a909-4090-94d7-20506b24d9 2018-08-02
3 1         _EG.EGM.RailrdL:4530b123-b3cc-4a89-97b4-9a0fe5e5bc 2018-08-02
4 1         _EG.EGM.RailrdL:29fa8cf3-486a-4eb4-9d22-913546fa0c 2018-08-02
5 1         _EG.EGM.RailrdL:7bb2cccd-76b6-4a84-9dfc-addc8993f1 2018-08-02
6 1         _EG.EGM.RailrdL:cc3ce7a7-15d7-41a5-8772-4a3008c181 2018-08-02
  F_CODE ICC EXS FCO GAW LLE NAMN1 ⋯ RCO RGC RRA RRC RSD RSU TEN TUC
1 AN010  FR  28  3   144 1   UNK   ⋯ N_P 3   4   16  1   1   0   45
2 AN010  FR  28  3   144 1   UNK   ⋯ N_P 3   4   16  1   1   0   45
3 AN010  FR  28  2   144 1   UNK   ⋯ N_P 3   3   16  1   1   1   45
4 AN010  FR  28  2   144 1   UNK   ⋯ N_P 3   3   16  1   1   1   45
5 AN010  FR  28  2   144 1   UNK   ⋯ N_P 3   3   16  1   1   1   45
6 AN010  FR  28  2   144 1   UNK   ⋯ N_P 3   3   16  1   1   1   45
  SHAPE_Leng  geometry
1 0.001297655 LINESTRING (0.597256 43.649...
2 0.002134066 LINESTRING (0.5970595 43.64...
3 0.011175217 LINESTRING (-4.245889 48.45...
4 0.006012132 LINESTRING (0.195875 49.509...
5 0.004340739 LINESTRING (0.192011 49.505...
6 0.867187818 LINESTRING (-1.619002 49.63...

In [48]:
wkt_to_array <- function(wkt) {
  # Remove the "LINESTRING" part and the parentheses
  coords <- gsub("LINESTRING \\(|\\)", "", wkt)
  # Split the string into individual coordinate pairs
  coords <- strsplit(coords, ",")[[1]]
  # Split each pair into individual coordinates, trim whitespace, and convert to numeric
  coords <- lapply(coords, function(coord) {
    coord_parts <- unlist(strsplit(trimws(coord), " "))
    as.numeric(coord_parts)
  })
  # Convert the list to a matrix
  do.call(rbind, coords)
}

"LINESTRING (0.597256 43.64945, 0.597414 43.65074)"

In [49]:
prova<- wkt_to_array(railLshp[1,25])

Warning message in FUN(X[[i]], ...):
"NAs introduced by coercion"

In [50]:
prova

     [,1]
[1,]        NA
[2,]  0.597414
[3,] 43.649447
[4,] 43.650735